name: Documentation

on:
  push:
    branches:
      - develop

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: prepare
      run: | 
        sudo apt-get install -y doxygen
        git submodule foreach 'git config -f .gitmodules submodule.$sm_path.shallow true'
        git submodule update --init --recursive

    - name: configure
      run: cmake . -Bbuild -Ddocumentation=ON -Dtests=OFF -Dcoverage=OFF

    - name: build
      run: cmake --build build --target Documentation --config Release -j4
      
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/documentation/doxygen/html
