name: Macos

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: configure
      run: cmake . -Bbuild

    - name: build
      run: cmake --build build --config Release -j4

    - name: test
      run: |
        cd build
        ctest --build-config Release
