name: Ubuntu

on:
  pull_request_review:
    types: [submitted]
    branches:
      - develop

  pull_request:
    types: [ review_requested ]
    branches:
      - develop

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    if: github.event.review.state == 'approved' || github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: configure
      run: cmake . -Bbuild

    - name: build
      run: cmake --build build --config Release -j4

    - name: test
      run: |
        cd build
        ctest --build-config Release
